sudo: required
services:
  - docker

node_js:
  - "11.10.1"

before_install:
  - docker build -t meskalin/docker-react -f Dockerfile.dev .

script:
  - docker run meskalin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-876166483902"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
